begin;
select set_config('test.a',gen_random_uuid()::text,true);
select set_config('test.b',gen_random_uuid()::text,true);
select set_config('test.c',gen_random_uuid()::text,true);
select set_config('test.post',gen_random_uuid()::text,true);
select set_config('test.story',gen_random_uuid()::text,true);
select set_config('test.comment',gen_random_uuid()::text,true);
select set_config('test.msg',gen_random_uuid()::text,true);
select set_config('test.chat',gen_random_uuid()::text,true);
insert into auth.users(id,aud,role,email) select current_setting('test.'||x)::uuid,'authenticated','authenticated',x||'-safety@example.invalid' from unnest(array['a','b','c'])x;
insert into public.profiles(id,display_name,username,bio) select current_setting('test.'||x)::uuid,'Prueba '||x,'safe_'||substr(replace(current_setting('test.'||x),'-',''),1,15),'Temporal' from unnest(array['a','b','c'])x;
select set_config('request.jwt.claim.sub',current_setting('test.b'),true);
insert into storage.objects(bucket_id,name,metadata) values('review-media',current_setting('test.b')||'/safe.jpg','{"size":128,"mimetype":"image/jpeg"}'),('review-media',current_setting('test.b')||'/story.jpg','{"size":128,"mimetype":"image/jpeg"}');
insert into public.posts(id,user_id,author_name,category,place,kind,media_path) values(current_setting('test.post')::uuid,current_setting('test.b')::uuid,'','Comer','Prueba','image',current_setting('test.b')||'/safe.jpg');
insert into public.stories(id,user_id,author_name,kind,media_path) values(current_setting('test.story')::uuid,current_setting('test.b')::uuid,'','image',current_setting('test.b')||'/story.jpg');
insert into public.comments(id,user_id,post_id,author_name,body) values(current_setting('test.comment')::uuid,current_setting('test.b')::uuid,current_setting('test.post')::uuid,'','Comentario temporal');
insert into public.conversations(id,user_low,user_high) values(current_setting('test.chat')::uuid,least(current_setting('test.a')::uuid,current_setting('test.b')::uuid),greatest(current_setting('test.a')::uuid,current_setting('test.b')::uuid));
insert into public.messages(id,conversation_id,sender_id,body) values(current_setting('test.msg')::uuid,current_setting('test.chat')::uuid,current_setting('test.b')::uuid,'Mensaje temporal');
insert into public.follows(follower_id,followed_id) values(current_setting('test.a')::uuid,current_setting('test.b')::uuid),(current_setting('test.b')::uuid,current_setting('test.a')::uuid);
insert into public.moderators(user_id) values(current_setting('test.c')::uuid);
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('test.a'),true);
insert into public.content_reports(reporter_id,target_kind,target_id,reason,details) values(current_setting('test.a')::uuid,'profile',current_setting('test.b')::uuid,'Spam','Caso de prueba');
select set_config('test.r_profile',(select id::text from public.content_reports where target_kind='profile'),true);
insert into public.content_reports(reporter_id,target_kind,target_id,reason,details) values(current_setting('test.a')::uuid,'post',current_setting('test.post')::uuid,'Spam','Caso de prueba');
select set_config('test.r_post',(select id::text from public.content_reports where target_kind='post'),true);
insert into public.content_reports(reporter_id,target_kind,target_id,reason,details) values(current_setting('test.a')::uuid,'story',current_setting('test.story')::uuid,'Spam','Caso de prueba');
select set_config('test.r_story',(select id::text from public.content_reports where target_kind='story'),true);
insert into public.content_reports(reporter_id,target_kind,target_id,reason,details) values(current_setting('test.a')::uuid,'comment',current_setting('test.comment')::uuid,'Spam','Caso de prueba');
select set_config('test.r_comment',(select id::text from public.content_reports where target_kind='comment'),true);
insert into public.content_reports(reporter_id,target_kind,target_id,reason,details) values(current_setting('test.a')::uuid,'message',current_setting('test.msg')::uuid,'Spam','Caso de prueba');
select set_config('test.r_message',(select id::text from public.content_reports where target_kind='message'),true);
select set_config('test.ordinary_not_admin',(not public.is_moderator())::text,true);
do $$ begin begin insert into public.moderators(user_id) values(current_setting('test.a')::uuid);perform set_config('test.no_self_promotion','false',true);exception when insufficient_privilege then perform set_config('test.no_self_promotion','true',true);end;end $$;
do $$ begin begin perform public.moderation_queue('pending');perform set_config('test.private_queue','false',true);exception when insufficient_privilege then perform set_config('test.private_queue','true',true);end;end $$;
do $$ begin begin perform public.moderation_report(current_setting('test.r_message')::uuid);perform set_config('test.private_report','false',true);exception when insufficient_privilege then perform set_config('test.private_report','true',true);end;end $$;
do $$ begin begin perform public.moderation_decide(current_setting('test.r_post')::uuid,'hide','Intento',0,gen_random_uuid());perform set_config('test.cannot_hide','false',true);exception when insufficient_privilege then perform set_config('test.cannot_hide','true',true);end;end $$;
do $$ begin begin insert into public.moderation_holds(target_kind,target_id,updated_by) values('post',current_setting('test.post')::uuid,current_setting('test.a')::uuid);perform set_config('test.no_direct_holds','false',true);exception when insufficient_privilege then perform set_config('test.no_direct_holds','true',true);end;end $$;
select set_config('request.jwt.claim.sub',current_setting('test.c'),true);
select set_config('test.admin_allowed',(public.is_moderator())::text,true);
select set_config('test.admin_queue',(exists(select 1 from jsonb_array_elements(public.moderation_queue('pending')) x where x->>'id'=current_setting('test.r_post')))::text,true);
select set_config('test.reported_message_only',(public.moderation_report(current_setting('test.r_message')::uuid)->>'preview'='Mensaje temporal' and not(public.moderation_report(current_setting('test.r_message')::uuid)?'reporter_id'))::text,true);
do $$ begin begin select * from public.moderators;perform set_config('test.no_client_membership_read','false',true);exception when insufficient_privilege then perform set_config('test.no_client_membership_read','true',true);end;end $$;
do $$ begin begin update public.moderation_audit set note='Otra nota';perform set_config('test.no_direct_audit_edits','false',true);exception when insufficient_privilege then perform set_config('test.no_direct_audit_edits','true',true);end;end $$;
do $$ begin begin perform public.moderation_decide(current_setting('test.r_post')::uuid,'remove','Nota válida',0,gen_random_uuid());perform set_config('test.invalid_action','false',true);exception when raise_exception then perform set_config('test.invalid_action','true',true);end;end $$;
do $$ begin begin perform public.moderation_decide(current_setting('test.r_post')::uuid,'hide','a',0,gen_random_uuid());perform set_config('test.short_note','false',true);exception when raise_exception then perform set_config('test.short_note','true',true);end;end $$;
do $$ begin begin perform public.moderation_decide(current_setting('test.r_post')::uuid,'hide','Motivo',null,gen_random_uuid());perform set_config('test.null_version','false',true);exception when raise_exception then perform set_config('test.null_version','true',true);end;end $$;
select set_config('test.request',gen_random_uuid()::text,true);
select public.moderation_decide(current_setting('test.r_post')::uuid,'hide','Ocultación de prueba',0,current_setting('test.request')::uuid);
select public.moderation_decide(current_setting('test.r_post')::uuid,'hide','Ocultación de prueba',0,current_setting('test.request')::uuid);
select set_config('test.hide_and_unique_audit',(public.content_hidden('post',current_setting('test.post')::uuid) and jsonb_array_length(public.moderation_report(current_setting('test.r_post')::uuid)->'history')=1 and (public.moderation_report(current_setting('test.r_post')::uuid)->>'review_version')::int=1)::text,true);
select set_config('test.reported_media_access',(public.reported_media(current_setting('test.b')||'/safe.jpg') and not public.reported_media(current_setting('test.b')||'/unreported.jpg'))::text,true);
do $$ begin begin perform public.moderation_decide(current_setting('test.r_post')::uuid,'restore','Restaurar prueba',0,gen_random_uuid());perform set_config('test.stale_decision','false',true);exception when raise_exception then perform set_config('test.stale_decision','true',true);end;end $$;
select set_config('request.jwt.claim.sub',current_setting('test.a'),true);
select set_config('test.hidden_from_user',((select count(*) from public.posts where id=current_setting('test.post')::uuid)=0 and (select count(*) from public.post_stats where post_id=current_setting('test.post')::uuid)=0 and (select count(*) from storage.objects where name=current_setting('test.b')||'/safe.jpg')=0)::text,true);
do $$ begin begin insert into public.bookmarks(user_id,post_id) values(current_setting('test.a')::uuid,current_setting('test.post')::uuid);perform set_config('test.hidden_interaction','false',true);exception when insufficient_privilege then perform set_config('test.hidden_interaction','true',true);end;end $$;
set local role anon;select set_config('request.jwt.claim.sub','',true);
select set_config('test.hidden_from_visitor',((select count(*) from public.posts where id=current_setting('test.post')::uuid)=0)::text,true);
do $$ begin begin perform public.moderation_queue('pending');perform set_config('test.anonymous_admin','false',true);exception when insufficient_privilege then perform set_config('test.anonymous_admin','true',true);end;end $$;
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('test.c'),true);
select public.moderation_decide(current_setting('test.r_post')::uuid,'restore','Restauración de prueba',1,gen_random_uuid());
select set_config('test.restored_audit',(not public.content_hidden('post',current_setting('test.post')::uuid) and jsonb_array_length(public.moderation_report(current_setting('test.r_post')::uuid)->'history')=2)::text,true);
select set_config('request.jwt.claim.sub',current_setting('test.a'),true);
select set_config('test.restored_visible',((select count(*) from public.posts where id=current_setting('test.post')::uuid)=1)::text,true);
select set_config('request.jwt.claim.sub',current_setting('test.c'),true);
select public.moderation_decide(current_setting('test.r_story')::uuid,'hide','Caso de prueba story',0,gen_random_uuid());
select public.moderation_decide(current_setting('test.r_comment')::uuid,'hide','Caso de prueba comment',0,gen_random_uuid());
select public.moderation_decide(current_setting('test.r_message')::uuid,'hide','Caso de prueba message',0,gen_random_uuid());
select set_config('request.jwt.claim.sub',current_setting('test.a'),true);
select set_config('test.all_types_hidden',((select count(*) from public.stories where id=current_setting('test.story')::uuid)=0 and (select count(*) from public.comments where id=current_setting('test.comment')::uuid)=0 and (select count(*) from public.messages where id=current_setting('test.msg')::uuid)=0)::text,true);
select set_config('test.comment_count_hidden',((select comments_count from public.post_stats where post_id=current_setting('test.post')::uuid)=0)::text,true);
select set_config('request.jwt.claim.sub',current_setting('test.b'),true);
update public.comments set deleted_at=null where id=current_setting('test.comment')::uuid;
select set_config('test.owner_cannot_override',(public.content_hidden('comment',current_setting('test.comment')::uuid) and (select count(*) from public.comments where id=current_setting('test.comment')::uuid)=0)::text,true);
select set_config('request.jwt.claim.sub',current_setting('test.c'),true);
select public.moderation_decide(current_setting('test.r_story')::uuid,'restore','Restaurar prueba story',1,gen_random_uuid());
select public.moderation_decide(current_setting('test.r_comment')::uuid,'restore','Restaurar prueba comment',1,gen_random_uuid());
select public.moderation_decide(current_setting('test.r_message')::uuid,'restore','Restaurar prueba message',1,gen_random_uuid());
do $$ begin begin perform public.moderation_decide(current_setting('test.r_profile')::uuid,'hide','Perfil de prueba',0,gen_random_uuid());perform set_config('test.profile_no_suspend','false',true);exception when raise_exception then perform set_config('test.profile_no_suspend','true',true);end;end $$;
select public.moderation_decide(current_setting('test.r_profile')::uuid,'dismiss','No corresponde',0,gen_random_uuid());
select set_config('test.dismiss_status',(public.moderation_report(current_setting('test.r_profile')::uuid)->>'status'='dismissed')::text,true);
select public.moderation_decide(current_setting('test.r_profile')::uuid,'reopen','Nueva revisión',1,gen_random_uuid());
select set_config('test.reopened',(public.moderation_report(current_setting('test.r_profile')::uuid)->>'status'='pending')::text,true);
select public.moderation_decide(current_setting('test.r_profile')::uuid,'review','Revisión terminada',2,gen_random_uuid());
select set_config('test.reviewed_history',(jsonb_array_length(public.moderation_report(current_setting('test.r_profile')::uuid)->'history')=3 and public.moderation_report(current_setting('test.r_profile')::uuid)->>'status'='reviewed')::text,true);
set local role postgres;delete from public.moderators where user_id=current_setting('test.c')::uuid;set local role authenticated;
select set_config('test.permission_revoked',(not public.is_moderator())::text,true);
do $$ begin begin perform public.moderation_report(current_setting('test.r_post')::uuid);perform set_config('test.revoked_no_access','false',true);exception when insufficient_privilege then perform set_config('test.revoked_no_access','true',true);end;end $$;
select label as check_name,current_setting('test.'||label)='true' as passed from(values ('ordinary_not_admin'),('no_self_promotion'),('private_queue'),('private_report'),('cannot_hide'),('no_direct_holds'),('admin_allowed'),('admin_queue'),('reported_message_only'),('no_client_membership_read'),('no_direct_audit_edits'),('invalid_action'),('short_note'),('null_version'),('hide_and_unique_audit'),('reported_media_access'),('stale_decision'),('hidden_from_user'),('hidden_interaction'),('hidden_from_visitor'),('anonymous_admin'),('restored_audit'),('restored_visible'),('all_types_hidden'),('comment_count_hidden'),('owner_cannot_override'),('profile_no_suspend'),('dismiss_status'),('reopened'),('reviewed_history'),('permission_revoked'),('revoked_no_access'))checks(label);
rollback;
