begin;
select set_config('test.a',gen_random_uuid()::text,true);
select set_config('test.b',gen_random_uuid()::text,true);
select set_config('test.c',gen_random_uuid()::text,true);
select set_config('test.post',gen_random_uuid()::text,true);
select set_config('test.story',gen_random_uuid()::text,true);
select set_config('test.comment',gen_random_uuid()::text,true);
select set_config('test.msg',gen_random_uuid()::text,true);
select set_config('test.chat',gen_random_uuid()::text,true);
insert into auth.users(id,aud,role,email) select current_setting('test.'||x)::uuid,'authenticated','authenticated',x||'-safety@example.invalid' from unnest(array['a','b','c'])x;
insert into public.profiles(id,display_name,username,bio) select current_setting('test.'||x)::uuid,'Prueba '||x,'safe_'||substr(replace(current_setting('test.'||x),'-',''),1,15),'Temporal' from unnest(array['a','b','c'])x;
select set_config('request.jwt.claim.sub',current_setting('test.b'),true);
insert into storage.objects(bucket_id,name,metadata) values('review-media',current_setting('test.b')||'/safe.jpg','{"size":128,"mimetype":"image/jpeg"}'),('review-media',current_setting('test.b')||'/story.jpg','{"size":128,"mimetype":"image/jpeg"}');
insert into public.posts(id,user_id,author_name,category,place,kind,media_path) values(current_setting('test.post')::uuid,current_setting('test.b')::uuid,'','Comer','Prueba','image',current_setting('test.b')||'/safe.jpg');
insert into public.stories(id,user_id,author_name,kind,media_path) values(current_setting('test.story')::uuid,current_setting('test.b')::uuid,'','image',current_setting('test.b')||'/story.jpg');
insert into public.comments(id,user_id,post_id,author_name,body) values(current_setting('test.comment')::uuid,current_setting('test.b')::uuid,current_setting('test.post')::uuid,'','Comentario temporal');
insert into public.conversations(id,user_low,user_high) values(current_setting('test.chat')::uuid,least(current_setting('test.a')::uuid,current_setting('test.b')::uuid),greatest(current_setting('test.a')::uuid,current_setting('test.b')::uuid));
insert into public.messages(id,conversation_id,sender_id,body) values(current_setting('test.msg')::uuid,current_setting('test.chat')::uuid,current_setting('test.b')::uuid,'Mensaje temporal');
insert into public.follows(follower_id,followed_id) values(current_setting('test.a')::uuid,current_setting('test.b')::uuid),(current_setting('test.b')::uuid,current_setting('test.a')::uuid);
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('test.a'),true);
select set_config('test.initial_visible',((select count(*) from public.posts where id=current_setting('test.post')::uuid)=1)::text,true);
insert into public.content_reports(reporter_id,target_kind,target_id,reason,details) values(current_setting('test.a')::uuid,'profile',current_setting('test.b')::uuid,'Spam','Prueba sintética') on conflict(reporter_id,target_kind,target_id) do nothing;
insert into public.content_reports(reporter_id,target_kind,target_id,reason,details) values(current_setting('test.a')::uuid,'post',current_setting('test.post')::uuid,'Spam','Prueba sintética') on conflict(reporter_id,target_kind,target_id) do nothing;
insert into public.content_reports(reporter_id,target_kind,target_id,reason,details) values(current_setting('test.a')::uuid,'story',current_setting('test.story')::uuid,'Spam','Prueba sintética') on conflict(reporter_id,target_kind,target_id) do nothing;
insert into public.content_reports(reporter_id,target_kind,target_id,reason,details) values(current_setting('test.a')::uuid,'comment',current_setting('test.comment')::uuid,'Spam','Prueba sintética') on conflict(reporter_id,target_kind,target_id) do nothing;
insert into public.content_reports(reporter_id,target_kind,target_id,reason,details) values(current_setting('test.a')::uuid,'message',current_setting('test.msg')::uuid,'Spam','Prueba sintética') on conflict(reporter_id,target_kind,target_id) do nothing;
insert into public.content_reports(reporter_id,target_kind,target_id,reason) values(current_setting('test.a')::uuid,'post',current_setting('test.post')::uuid,'Otro') on conflict(reporter_id,target_kind,target_id) do nothing;
select set_config('test.reports_saved_unique',((select count(*) from public.content_reports)=5 and (select bool_and(target_owner=current_setting('test.b')::uuid and status='pending') from public.content_reports))::text,true);
do $$ begin begin insert into public.content_reports(reporter_id,target_kind,target_id,reason) values(current_setting('test.b')::uuid,'profile',current_setting('test.a')::uuid,'Spam');perform set_config('test.report_spoof','false',true);exception when insufficient_privilege then perform set_config('test.report_spoof','true',true);end;end $$;
do $$ begin begin insert into public.content_reports(reporter_id,target_kind,target_id,reason) values(current_setting('test.a')::uuid,'post',gen_random_uuid(),'Spam');perform set_config('test.report_invalid','false',true);exception when raise_exception then perform set_config('test.report_invalid','true',true);end;end $$;
do $$ begin begin insert into public.content_reports(reporter_id,target_kind,target_id,reason) values(current_setting('test.a')::uuid,'profile',current_setting('test.a')::uuid,'Spam');perform set_config('test.report_self','false',true);exception when check_violation then perform set_config('test.report_self','true',true);end;end $$;
do $$ begin begin update public.content_reports set status='dismissed';perform set_config('test.report_status','false',true);exception when insufficient_privilege then perform set_config('test.report_status','true',true);end;end $$;
do $$ begin begin insert into public.user_blocks(blocker_id,blocked_id) values(current_setting('test.b')::uuid,current_setting('test.c')::uuid);perform set_config('test.block_spoof','false',true);exception when insufficient_privilege then perform set_config('test.block_spoof','true',true);end;end $$;
do $$ begin begin insert into public.user_blocks(blocker_id,blocked_id) values(current_setting('test.a')::uuid,current_setting('test.a')::uuid);perform set_config('test.block_self','false',true);exception when check_violation then perform set_config('test.block_self','true',true);end;end $$;
insert into public.user_blocks(blocker_id,blocked_id) values(current_setting('test.a')::uuid,current_setting('test.b')::uuid);
insert into public.user_blocks(blocker_id,blocked_id) values(current_setting('test.a')::uuid,current_setting('test.b')::uuid) on conflict(blocker_id,blocked_id) do nothing;
select set_config('test.block_saved_unique',((select count(*) from public.user_blocks)=1 and (select blocked_name from public.user_blocks)='Prueba b')::text,true);
select set_config('test.content_hidden',((select count(*) from public.posts where id=current_setting('test.post')::uuid)=0 and (select count(*) from public.stories where id=current_setting('test.story')::uuid)=0 and (select count(*) from public.comments where id=current_setting('test.comment')::uuid)=0)::text,true);
select set_config('test.profile_hidden',((select count(*) from public.public_profiles where id=current_setting('test.b')::uuid)=0)::text,true);
select set_config('test.chat_hidden',((select count(*) from public.conversations)=0 and (select count(*) from public.messages)=0 and (select count(*) from public.chat_inbox)=0)::text,true);
select set_config('test.follow_removed',((select count(*) from public.follows)=0)::text,true);
select set_config('test.notices_hidden',((select count(*) from public.notifications)=0)::text,true);
do $$ begin begin insert into public.messages(id,conversation_id,sender_id,body) values(gen_random_uuid(),current_setting('test.chat')::uuid,current_setting('test.a')::uuid,'No permitido');perform set_config('test.send_blocked','false',true);exception when insufficient_privilege then perform set_config('test.send_blocked','true',true);end;end $$;
do $$ begin begin insert into public.follows(follower_id,followed_id) values(current_setting('test.a')::uuid,current_setting('test.b')::uuid);perform set_config('test.follow_blocked','false',true);exception when insufficient_privilege then perform set_config('test.follow_blocked','true',true);end;end $$;
do $$ begin begin insert into public.post_likes(user_id,post_id) values(current_setting('test.a')::uuid,current_setting('test.post')::uuid);perform set_config('test.like_blocked','false',true);exception when insufficient_privilege then perform set_config('test.like_blocked','true',true);end;end $$;
do $$ begin begin insert into public.comments(user_id,post_id,author_name,body) values(current_setting('test.a')::uuid,current_setting('test.post')::uuid,'','No permitido');perform set_config('test.comment_blocked','false',true);exception when insufficient_privilege then perform set_config('test.comment_blocked','true',true);end;end $$;
select set_config('request.jwt.claim.sub',current_setting('test.b'),true);
select set_config('test.reverse_block',(public.blocked_with(current_setting('test.a')::uuid) and (select count(*) from public.public_profiles where id=current_setting('test.a')::uuid)=0 and (select count(*) from public.messages)=0)::text,true);
select set_config('test.reports_private',((select count(*) from public.content_reports)=0 and (select count(*) from public.user_blocks)=0)::text,true);
delete from public.user_blocks where blocked_id=current_setting('test.b')::uuid;
select set_config('request.jwt.claim.sub',current_setting('test.c'),true);
do $$ begin begin insert into public.content_reports(reporter_id,target_kind,target_id,reason) values(current_setting('test.c')::uuid,'message',current_setting('test.msg')::uuid,'Spam');perform set_config('test.private_message_report','false',true);exception when raise_exception then perform set_config('test.private_message_report','true',true);end;end $$;
select set_config('test.third_unaffected',(not public.blocked_with(current_setting('test.b')::uuid) and (select count(*) from public.posts where id=current_setting('test.post')::uuid)=1 and (select count(*) from public.user_blocks)=0)::text,true);
select set_config('request.jwt.claim.sub',current_setting('test.a'),true);
select set_config('test.other_cannot_unblock',(public.blocked_with(current_setting('test.b')::uuid))::text,true);
delete from public.user_blocks where blocker_id=current_setting('test.a')::uuid and blocked_id=current_setting('test.b')::uuid;
select set_config('test.unblock_restores',(not public.blocked_with(current_setting('test.b')::uuid) and (select count(*) from public.messages)=1 and (select count(*) from public.posts where id=current_setting('test.post')::uuid)=1 and (select count(*) from public.public_profiles where id=current_setting('test.b')::uuid)=1 and (select count(*) from public.follows)=0)::text,true);
set local role anon;
select set_config('request.jwt.claim.sub','',true);
do $$ begin begin select * from public.content_reports;perform set_config('test.anonymous_reports','false',true);exception when insufficient_privilege then perform set_config('test.anonymous_reports','true',true);end;end $$;
do $$ begin begin select * from public.user_blocks;perform set_config('test.anonymous_blocks','false',true);exception when insufficient_privilege then perform set_config('test.anonymous_blocks','true',true);end;end $$;
select set_config('test.public_still_visible',((select count(*) from public.posts where id=current_setting('test.post')::uuid)=1)::text,true);
select label as check_name,current_setting('test.'||label)='true' as passed from(values ('initial_visible'),('reports_saved_unique'),('report_spoof'),('report_invalid'),('report_self'),('report_status'),('block_spoof'),('block_self'),('block_saved_unique'),('content_hidden'),('profile_hidden'),('chat_hidden'),('follow_removed'),('notices_hidden'),('send_blocked'),('follow_blocked'),('like_blocked'),('comment_blocked'),('reverse_block'),('reports_private'),('private_message_report'),('third_unaffected'),('other_cannot_unblock'),('unblock_restores'),('anonymous_reports'),('anonymous_blocks'),('public_still_visible'))checks(label);
rollback;
