import React, {useState} from 'react';
import {View, Text, ScrollView, Pressable, StyleSheet, Image, Modal, TextInput, Platform, PanResponder, useWindowDimensions} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import * as ImagePicker from 'expo-image-picker';
import {VideoView, useVideoPlayer} from 'expo-video';

type Media = {uri:string; type:'image'|'video'};
type Review = {id:string; category:string; place:string; text:string; author:string; color:string; symbol:string; media?:Media};
const seed:Review[] = [
 {id:'1',category:'Comer',place:'Café del Patio',text:'Café tranquilo, luz de tarde y una mesa para conversar. Lo recomendaría para ir sin prisa con un amigo.',author:'Ana · Ficticia',color:'#b68158',symbol:'☕'},
 {id:'2',category:'Divertirse',place:'Foro Noche',text:'Un escenario pequeño y un ambiente relajado. Llegaría temprano para elegir un buen lugar.',author:'Luis · Ficticio',color:'#716b9b',symbol:'♫'},
 {id:'3',category:'Explorar',place:'Galería Abierta',text:'Caminar sin itinerario y detenerse en los detalles. Un buen plan para una mañana libre.',author:'Mar · Ficticia',color:'#668773',symbol:'◈'},
];
function Video({uri,onEnd}:{uri:string;onEnd?:()=>void}){
 const player=useVideoPlayer(uri,p=>{p.loop=false;});
 React.useEffect(()=>{if(!onEnd)return;const subscription=player.addListener('playToEnd',onEnd);return()=>subscription.remove();},[player,onEnd]);
 return <VideoView player={player} style={StyleSheet.absoluteFill} nativeControls contentFit="cover" />;
}
function MediaCard({review,saved,toggle,open,height}:{review:Review;saved:boolean;toggle:()=>void;open:()=>void;height:number}){
 const [ended,setEnded]=useState(false);
 const gesture=React.useMemo(()=>PanResponder.create({onMoveShouldSetPanResponder:(_,g)=>g.dy < -18 && Math.abs(g.dy)>Math.abs(g.dx)*1.5,onPanResponderRelease:(_,g)=>{if(g.dy < -45)open();}}),[open]);
 return <View style={[s.mediaCard,{height,backgroundColor:review.color}]}>
  {review.media?.type==='video'?<Video uri={review.media.uri} onEnd={()=>setEnded(true)}/>:review.media?<Image source={{uri:review.media.uri}} style={StyleSheet.absoluteFill} resizeMode="cover"/>:<View style={s.placeholder}><Text style={s.symbol}>{review.symbol}</Text><Text style={s.placeholderText}>ESPACIO PARA FOTO O VIDEO</Text><Text style={s.placeholderText}>MAQUETA · LUGAR FICTICIO</Text></View>}
  <View pointerEvents="none" style={s.topOverlay}><Text style={s.category}>{review.category.toUpperCase()}</Text></View>
  <View style={s.actions}><Pressable accessibilityRole="button" accessibilityLabel={saved?'Quitar de pendientes':'Guardar en pendientes'} onPress={toggle} style={s.circle}><Text style={s.actionIcon}>{saved?'♥':'♡'}</Text></Pressable></View>
  <View style={s.bottomOverlay}><Text style={s.author}>{review.author}</Text><Text style={s.place}>{review.place}</Text><View {...gesture.panHandlers}><Pressable accessibilityRole="button" accessibilityLabel={'Ver detalles de '+review.place} onPress={open} style={s.detailsButton}><Text style={s.detailsText}>↑ {ended?'¿Te interesa? Ver detalles':'Desliza aquí hacia arriba · Ver detalles'}</Text></Pressable></View></View>
 </View>;
}
export default function App(){
 const {height}=useWindowDimensions();
 const [tab,setTab]=useState('Inicio'),[filter,setFilter]=useState('Todo'),[reviews,setReviews]=useState(seed),[saved,setSaved]=useState<string[]>([]),[detail,setDetail]=useState<Review|null>(null);
 const [media,setMedia]=useState<Media|null>(null),[place,setPlace]=useState(''),[text,setText]=useState(''),[category,setCategory]=useState('Comer'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const toggle=(id:string)=>setSaved(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);
 const button=(label:string,fn:()=>void,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled} onPress={fn} style={[s.button,disabled&&{opacity:.5}]}><Text style={s.buttonText}>{label}</Text></Pressable>;
 const pick=async()=>{setError('');setBusy(true);try{const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images','videos'],allowsEditing:false,quality:.85});if(!result.canceled){const asset=result.assets[0];if(asset.type!=='image'&&asset.type!=='video'){setError('Selecciona una foto o un video.');return;}if(asset.fileSize&&asset.fileSize>100*1024*1024){setError('Para esta demo usa un archivo menor de 100 MB.');return;}if(asset.type==='video'&&asset.duration&&asset.duration>60000){setError('Para esta demo elige un video de hasta 60 segundos.');return;}setMedia({uri:asset.uri,type:asset.type});}}catch{setError('No se pudo abrir el archivo. Revisa el permiso o prueba otro formato.');}finally{setBusy(false);}};
 const publish=()=>{if(!media){setError('Selecciona una foto o un video. No se publican reseñas de solo texto.');return;}if(place.trim().length<2){setError('Escribe el nombre del lugar.');return;}setReviews(p=>[{id:Date.now().toString(),category,place:place.trim(),text:text.trim(),author:'Tú · Prueba local',color:'#2b3933',symbol:'↗',media},...p]);setMedia(null);setPlace('');setText('');setError('');setFilter('Todo');setTab('Inicio');};
 const list=reviews.filter(r=>(tab!=='Pendientes'||saved.includes(r.id))&&(filter==='Todo'||r.category===filter));
 return <View style={s.app}><StatusBar style="light"/><View style={s.header}><Text style={s.brand}>por ahí ↗</Text><Text style={s.label}>FOTOS + VIDEOS · DEMO</Text></View>
 <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
 {(tab==='Inicio'||tab==='Pendientes')&&<><View style={s.filters}>{['Todo','Comer','Divertirse','Explorar'].map(c=><Pressable key={c} accessibilityRole="button" accessibilityState={{selected:filter===c}} onPress={()=>setFilter(c)} style={[s.chip,filter===c&&s.chipActive]}><Text style={s.chipText}>{c}</Text></Pressable>)}</View><Text style={s.demo}>{tab==='Pendientes'?'Tus planes guardados.':'Maquetas visuales. Añade una foto o video en Publicar para probar contenido real.'}</Text>{list.map(r=><MediaCard key={r.id} review={r} saved={saved.includes(r.id)} toggle={()=>toggle(r.id)} open={()=>setDetail(r)} height={Math.max(420,Math.min(720,height-195))}/>)}{!list.length&&<Text style={s.body}>Guarda una foto o video desde Inicio para crear tus pendientes.</Text>}</>}
 {tab==='Publicar'&&<View style={s.form}><Text style={s.title}>Primero, la experiencia.</Text><Text style={s.body}>Elige una foto o video. Los detalles se muestran solo cuando alguien los abre.</Text>{button(busy?'Abriendo…':media?'Cambiar foto o video':'Elegir foto o video',pick,busy)}{media&&<View style={s.preview}>{media.type==='image'?<Image source={{uri:media.uri}} style={StyleSheet.absoluteFill} resizeMode="cover"/>:<Video uri={media.uri}/>}</View>}<Text style={s.fieldLabel}>Lugar</Text><TextInput accessibilityLabel="Lugar" value={place} onChangeText={setPlace} maxLength={100} style={s.input} placeholder="¿Dónde fue?" placeholderTextColor="#a0aca3"/><Text style={s.fieldLabel}>Categoría</Text><View style={s.filters}>{['Comer','Divertirse','Explorar'].map(c=><Pressable key={c} accessibilityRole="button" onPress={()=>setCategory(c)} style={[s.chip,category===c&&s.chipActive]}><Text style={s.chipText}>{c}</Text></Pressable>)}</View><Text style={s.fieldLabel}>Información adicional · opcional</Text><TextInput accessibilityLabel="Información adicional" value={text} onChangeText={setText} multiline maxLength={1500} style={[s.input,{minHeight:110,textAlignVertical:'top'}]} placeholder="Tu opinión, presupuesto, consejos…" placeholderTextColor="#a0aca3"/>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}{button('Publicar en esta demo',publish,busy)}<Text style={s.demo}>Solo en este dispositivo, sin subir archivos a internet. Se pierde al reiniciar. Videos de hasta 60 s y archivos de hasta 100 MB cuando el selector informa esos datos.</Text></View>}
 {tab==='Perfil'&&<View style={s.form}><Text style={s.title}>Tu mirada, tu perfil.</Text><Text style={s.body}>{reviews.length-seed.length} experiencias · {saved.length} pendientes</Text><Text style={s.demo}>Perfil de prueba. Cuentas, seguidores y buscador aún pendientes.</Text>{reviews.filter(r=>!seed.some(x=>x.id===r.id)).map(r=><MediaCard key={r.id} review={r} saved={saved.includes(r.id)} toggle={()=>toggle(r.id)} open={()=>setDetail(r)} height={420}/>)}</View>}
 </ScrollView><View style={s.nav}>{['Inicio','Pendientes','Publicar','Perfil'].map(t=><Pressable key={t} accessibilityRole="button" accessibilityState={{selected:tab===t}} onPress={()=>{setTab(t);setFilter('Todo');}} style={s.navItem}><Text style={[s.navText,tab===t&&{color:'#f4b77f'}]}>{t}</Text></Pressable>)}</View>
 <Modal visible={!!detail} transparent animationType="slide" onRequestClose={()=>setDetail(null)}><View style={s.modalBackdrop}><Pressable accessibilityRole="button" accessibilityLabel="Cerrar detalles" onPress={()=>setDetail(null)} style={{flex:1}}/><View style={s.sheet}><View style={s.handle}/><ScrollView contentContainerStyle={{padding:24}}>{detail&&<><Text style={s.label}>{detail.category.toUpperCase()}</Text><Text style={s.title}>{detail.place}</Text><Text style={s.body}>{detail.text||'La persona no agregó información adicional.'}</Text><Text style={s.demo}>{detail.author} · {detail.media?'Publicación local de prueba':'Lugar y reseña ficticios'}</Text>{button(saved.includes(detail.id)?'Quitar de pendientes':'Guardar en pendientes',()=>toggle(detail.id))}{button('Cerrar detalles',()=>setDetail(null))}</>}</ScrollView></View></View></Modal>
 </View>;
}
const s=StyleSheet.create({app:{flex:1,backgroundColor:'#101a16'},header:{paddingTop:Platform.OS==='ios'?58:25,paddingHorizontal:22,paddingBottom:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},brand:{fontSize:29,fontWeight:'800',color:'#fff',letterSpacing:-1},label:{fontSize:9,letterSpacing:1.5,color:'#d8b58e'},content:{width:'100%',maxWidth:590,alignSelf:'center',paddingBottom:16},filters:{flexDirection:'row',gap:8,flexWrap:'wrap',paddingHorizontal:16,paddingVertical:10},chip:{paddingHorizontal:14,paddingVertical:10,borderRadius:22,backgroundColor:'#24372b'},chipActive:{backgroundColor:'#935136'},chipText:{color:'#f6f5ed',fontSize:12},demo:{color:'#adb6aa',fontSize:11,lineHeight:18,paddingHorizontal:18,marginVertical:12},mediaCard:{marginHorizontal:12,marginBottom:14,borderRadius:22,overflow:'hidden'},placeholder:{flex:1,justifyContent:'center',alignItems:'center',gap:14},symbol:{fontSize:110,color:'#ead9c8'},placeholderText:{fontSize:9,letterSpacing:2,color:'#fff'},topOverlay:{position:'absolute',top:20,left:20},category:{fontSize:9,letterSpacing:2,color:'#fff',backgroundColor:'#0008',padding:9,borderRadius:12},bottomOverlay:{position:'absolute',left:0,right:0,bottom:0,padding:20,backgroundColor:'#0009'},author:{fontSize:12,color:'#e8e9e2',marginBottom:8},place:{fontSize:25,fontWeight:'700',color:'#fff',marginBottom:15},detailsButton:{padding:15,borderRadius:15,backgroundColor:'#ffffff25',minHeight:48},detailsText:{color:'#fff',fontSize:12,fontWeight:'700',textAlign:'center'},actions:{position:'absolute',right:16,bottom:170},circle:{width:48,height:48,borderRadius:25,backgroundColor:'#0008',alignItems:'center',justifyContent:'center'},actionIcon:{fontSize:28,color:'#fff'},nav:{flexDirection:'row',paddingTop:5,paddingBottom:Platform.OS==='ios'?30:12,borderTopWidth:1,borderColor:'#2a3b2e'},navItem:{flex:1,alignItems:'center',paddingVertical:16},navText:{fontSize:12,fontWeight:'600',color:'#c7d0c3'},form:{padding:22},title:{fontSize:30,lineHeight:36,fontWeight:'700',color:'#f5f3e9',marginVertical:16},body:{fontSize:15,lineHeight:25,color:'#d0d7c8',paddingHorizontal:4,marginBottom:20},button:{padding:16,borderRadius:12,backgroundColor:'#965337',marginVertical:6,alignItems:'center'},buttonText:{fontSize:13,color:'#fff',fontWeight:'700'},fieldLabel:{fontSize:12,color:'#e1d5c1',marginTop:22,marginBottom:10},input:{padding:15,borderRadius:12,backgroundColor:'#233429',color:'#fff',fontSize:15},preview:{height:250,borderRadius:15,overflow:'hidden',marginTop:16},error:{color:'#ffb8a2',fontSize:13,marginVertical:16},modalBackdrop:{flex:1,backgroundColor:'#0008'},sheet:{maxHeight:'78%',backgroundColor:'#18281e',borderTopLeftRadius:26,borderTopRightRadius:26,paddingBottom:Platform.OS==='ios'?24:8},handle:{alignSelf:'center',width:42,height:4,borderRadius:4,backgroundColor:'#637261',marginTop:12}});
