import React,{useCallback,useEffect,useRef,useState} from 'react';
import {View,Text,TextInput,Pressable,StyleSheet} from 'react-native';
import type {ReportTarget} from '../lib/safety';
import {loadComments,addComment,removeComment,commentId,type Comment} from '../lib/interactions';
import {palette as p} from '../lib/theme';
import Icon from './Icon';
export default function Comments({postId,userId,onChange,report}:{postId:string;userId:string|null;onChange:()=>void;report:(target:ReportTarget)=>void}){
 const [rows,setRows]=useState<Comment[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[draft,setDraft]=useState(''),[removed,setRemoved]=useState<string|null>(null);
 const draftId=useRef(''),mounted=useRef(true),lock=useRef(false);
 const reload=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const data=await loadComments(postId,signal);if(mounted.current)setRows(data);}finally{if(mounted.current)setLoading(false);}},[postId]);
 useEffect(()=>{mounted.current=true;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);reload(controller.signal).catch(e=>{if(mounted.current)setError(e.message);});return()=>{mounted.current=false;clearTimeout(timeout);controller.abort();};},[reload]);
 const run=async(action:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await action();if(mounted.current){onChange();await reload();}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'No se pudo completar.');}finally{lock.current=false;if(mounted.current)setBusy(false);}};
 const button=(label:string,action:()=>void)=><Pressable accessibilityRole="button" disabled={busy} onPress={action} style={[s.button,busy&&{opacity:.5}]}><Text style={s.buttonText}>{label}</Text></Pressable>;
 return <View style={s.box}><View style={s.heading}><Text style={s.title}>La conversación</Text><Pressable accessibilityRole="button" accessibilityLabel="Actualizar comentarios" disabled={busy} onPress={()=>run(async()=>{})} style={s.refresh}><Icon name="refresh" size={21} color={p.muted}/></Pressable></View>{loading&&<Text style={s.note}>Cargando comentarios…</Text>}{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}
 {!loading&&!rows.length&&!error&&<Text style={s.note}>Todavía no hay comentarios.</Text>}
 {rows.map(row=><View key={row.id} style={s.comment}><View style={s.avatar}><Text style={s.initial}>{row.author_name[0]?.toUpperCase()}</Text></View><View style={{flex:1,minWidth:0}}><Text style={s.author}>{row.author_name}</Text><Text style={s.body}>{row.body}</Text>{row.user_id!==userId&&button('Reportar comentario',()=>report({kind:'comment',id:row.id,label:'Comentario de '+row.author_name}))}{row.user_id===userId&&button('Borrar mi comentario',()=>run(async()=>{await removeComment(userId,row.id);if(mounted.current)setRemoved(row.id);} ))}</View></View>)}
 {removed&&userId&&<View><Text style={s.note}>Comentario borrado.</Text>{button('Deshacer borrado',()=>run(async()=>{await removeComment(userId,removed,true);if(mounted.current)setRemoved(null);} ))}</View>}
 {userId?<><TextInput accessibilityLabel="Escribir comentario" value={draft} onChangeText={text=>{setDraft(text);draftId.current='';}} editable={!busy} maxLength={1000} multiline placeholder="Comparte tu opinión…" placeholderTextColor={p.muted} style={s.input}/><Pressable accessibilityRole="button" disabled={busy} style={[s.publish,busy&&{opacity:.5}]} onPress={()=>{if(!draft.trim()){setError('Escribe un comentario antes de publicar.');return;}if(!draftId.current)draftId.current=commentId();run(async()=>{await addComment(userId,postId,draft,draftId.current);if(mounted.current){setDraft('');draftId.current='';}});}}><Text style={s.publishText}>{busy?'Publicando…':'Publicar comentario'}</Text><Icon name="arrow" size={20}/></Pressable></>:<Text style={s.note}>Inicia sesión desde Perfil para comentar.</Text>}
 {rows.length===50&&<Text style={s.note}>Mostramos los últimos 50 comentarios.</Text>}
 </View>;
}
const s=StyleSheet.create({box:{marginTop:22,borderTopWidth:1,borderColor:p.line,paddingTop:14},heading:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},title:{fontSize:22,fontWeight:'800',letterSpacing:-.5,color:p.ink},refresh:{width:44,height:44,alignItems:'center',justifyContent:'center'},note:{color:p.muted,fontSize:12,lineHeight:20,marginVertical:10},error:{color:p.error,fontSize:13,lineHeight:21,marginVertical:10},comment:{flexDirection:'row',gap:10,paddingVertical:13,borderBottomWidth:1,borderColor:p.line,marginBottom:6},avatar:{width:30,height:30,borderRadius:11,backgroundColor:p.violetSoft,alignItems:'center',justifyContent:'center'},initial:{color:p.violet,fontWeight:'800',fontSize:12},author:{fontSize:12,fontWeight:'700',color:p.ink},body:{fontSize:14,lineHeight:23,color:p.ink,marginTop:5},input:{padding:15,borderRadius:15,backgroundColor:p.soft,color:p.ink,minHeight:85,fontSize:16,lineHeight:23,marginTop:12,textAlignVertical:'top'},button:{minHeight:44,justifyContent:'center',paddingVertical:10},buttonText:{color:p.muted,fontSize:10,fontWeight:'600'},publish:{minHeight:48,padding:14,borderRadius:15,backgroundColor:p.lime,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,marginTop:10},publishText:{fontSize:12,fontWeight:'800',color:p.ink}});
