import React,{useState,useEffect,useCallback,useRef} from 'react';
import {View,Text,Pressable,TextInput,ScrollView,StyleSheet,KeyboardAvoidingView,Platform} from 'react-native';
import {loadInbox,loadMessages,sendMessage,type Conversation,type Message} from '../lib/messages';
import type {ReportTarget} from '../lib/safety';
import {commentId} from '../lib/interactions';
const button=(label:string,action:()=>void,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled} onPress={action} style={[s.button,disabled&&{opacity:.5}]}><Text style={s.buttonText}>{label}</Text></Pressable>;
export function Inbox({userId,open,login}:{userId:string|null;open:(c:Conversation)=>void;login:()=>void}){
 const [rows,setRows]=useState<Conversation[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const alive=useRef(false),generation=useRef(0);
 const refresh=useCallback(async()=>{const g=++generation.current;setBusy(true);setError('');try{const data=await loadInbox();if(alive.current&&g===generation.current)setRows(data);}catch(e){if(alive.current&&g===generation.current)setError((e as Error).message);}finally{if(alive.current&&g===generation.current)setBusy(false);}},[]);
 useEffect(()=>{alive.current=true;if(!userId)return()=>{alive.current=false;};Promise.resolve().then(()=>{if(alive.current)refresh();});const id=setInterval(refresh,30000);return()=>{alive.current=false;clearInterval(id);};},[userId,refresh]);
 return <View style={s.content}><Text style={s.title}>Conversaciones</Text>{!userId?<><Text style={s.note}>Inicia sesión para conversar con otras personas.</Text>{button('Ir a mi cuenta',login)}</>:<><Text style={s.note}>Busca una persona, abre su perfil y pulsa Enviar mensaje.</Text>{button(busy?'Actualizando…':'Actualizar conversaciones',()=>refresh(),busy)}{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}{!busy&&!error&&!rows.length&&<Text style={s.note}>Todavía no tienes conversaciones.</Text>}{rows.map(c=><Pressable key={c.id} accessibilityRole="button" accessibilityLabel={'Conversación con '+c.peer_name} onPress={()=>open(c)} style={s.row}><Text style={s.name}>{c.peer_name} · @{c.peer_handle}</Text><Text numberOfLines={2} style={s.note}>{c.last_body||'Empieza una conversación…'}</Text></Pressable>)}{rows.length===50&&<Text style={s.note}>Mostramos las 50 conversaciones más recientes.</Text>}</>}</View>;
}
export function Chat({userId,conversation,close,report,block}:{userId:string;conversation:Conversation;close:()=>void;report:(target:ReportTarget)=>void;block:()=>void}){
 const [rows,setRows]=useState<Message[]>([]),[text,setText]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[sending,setSending]=useState(false);
 const alive=useRef(false),generation=useRef(0),lock=useRef(false),draftId=useRef('');
 const refresh=useCallback(async()=>{const g=++generation.current;setLoading(true);try{const data=await loadMessages(conversation.id);if(alive.current&&g===generation.current){setRows(data);setError('');}}catch(e){if(alive.current&&g===generation.current)setError((e as Error).message);}finally{if(alive.current&&g===generation.current)setLoading(false);}},[conversation.id]);
 useEffect(()=>{alive.current=true;Promise.resolve().then(()=>{if(alive.current)refresh();});const id=setInterval(refresh,15000);return()=>{alive.current=false;clearInterval(id);};},[refresh]);
 const send=async()=>{if(lock.current||!text.trim())return;lock.current=true;setSending(true);setError('');if(!draftId.current)draftId.current=commentId();try{await sendMessage(userId,conversation.id,text,draftId.current);if(alive.current){setText('');draftId.current='';await refresh();}}catch(e){if(alive.current)setError((e as Error).message);}finally{lock.current=false;if(alive.current)setSending(false);}};
 return <KeyboardAvoidingView style={s.screen} behavior={Platform.OS==='ios'?'padding':undefined}><View style={[s.content,{paddingTop:55}]}>{button('Volver a mensajes',close,sending)}<Text style={s.title}>{conversation.peer_name}</Text><Text style={s.note}>Conversación privada entre ambas cuentas.</Text>{button('Bloquear usuario',block,sending)}{button(loading?'Actualizando…':'Actualizar mensajes',()=>refresh(),loading||sending)}{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}</View><ScrollView style={{flex:1}} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">{!loading&&!rows.length&&<Text style={s.note}>Propón un plan o comparte una recomendación.</Text>}{rows.length===50&&<Text style={s.note}>Mostramos los últimos 50 mensajes.</Text>}{rows.map(m=><View key={m.id} style={[s.bubble,m.sender_id===userId&&s.own]}><Text style={s.name}>{m.sender_id===userId?'Tú':conversation.peer_name}</Text><Text style={s.body}>{m.body}</Text><Text style={s.date}>{new Date(m.created_at).toLocaleString('es-MX')}</Text>{m.sender_id!==userId&&button('Reportar mensaje',()=>report({kind:'message',id:m.id,label:'Mensaje de '+conversation.peer_name}),sending)}</View>)}</ScrollView><View style={[s.content,{paddingBottom:30}]}><TextInput accessibilityLabel="Mensaje" placeholder="Propón un plan…" placeholderTextColor="#758170" value={text} editable={!sending} onChangeText={value=>{setText(value);draftId.current='';}} multiline maxLength={1000} style={s.input}/>{button(sending?'Enviando…':'Enviar mensaje',()=>send(),sending||!text.trim())}<Text style={s.date}>Se actualiza cada 15 segundos mientras está abierta.</Text></View></KeyboardAvoidingView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#faf9f5'},content:{padding:22,width:'100%',maxWidth:590,alignSelf:'center'},title:{fontSize:28,fontWeight:'700',color:'#243d31',marginVertical:12},note:{fontSize:13,color:'#536350',lineHeight:21,marginVertical:10},row:{paddingVertical:15,borderBottomWidth:1,borderColor:'#e2e7d8'},name:{fontSize:14,fontWeight:'600',color:'#243d31'},body:{fontSize:15,lineHeight:23,color:'#243d31',marginVertical:8},date:{fontSize:11,color:'#66735e',marginTop:6},button:{backgroundColor:'#965337',padding:15,borderRadius:12,marginVertical:5},buttonText:{color:'#fff',textAlign:'center',fontWeight:'600'},error:{color:'#9c3d24',marginVertical:10},input:{backgroundColor:'#e9eee4',padding:15,borderRadius:12,color:'#243d31',maxHeight:110},bubble:{backgroundColor:'#eef1e8',padding:15,borderRadius:15,marginBottom:10,marginRight:25},own:{backgroundColor:'#e1e9d7',marginRight:0,marginLeft:25}});
