import React,{useCallback,useEffect,useRef,useState} from 'react';
import {View,Text,Pressable,ScrollView,TextInput,Image,StyleSheet} from 'react-native';
import {VideoView,useVideoPlayer} from 'expo-video';
import {loadModeration,loadReport,decideReport,decisionLabels,statusLabels,type Decision,type ReportStatus,type ReportRow,type ReportDetail} from '../lib/moderation';
import {commentId} from '../lib/interactions';
import {palette as p} from '../lib/theme';
import ui from '../lib/uiStyles';
import ScreenHeader from './ScreenHeader';
export function AdminButton({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button,disabled&&{opacity:.5}]}><Text style={s.buttonText}>{label}</Text></Pressable>;}
function ReportVideo({uri}:{uri:string}){const player=useVideoPlayer(uri,p=>{p.loop=false;});return <VideoView player={player} style={s.media} nativeControls contentFit="contain"/>;}
const kindLabels:Record<string,string>={profile:'Perfil',post:'Publicación',story:'Story',comment:'Comentario',message:'Mensaje'};
export default function Moderation({close}:{close:()=>void}){
 const [status,setStatus]=useState<ReportStatus>('pending'),[rows,setRows]=useState<ReportRow[]>([]),[detail,setDetail]=useState<ReportDetail|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[note,setNote]=useState(''),[action,setAction]=useState<Decision|null>(null);
 const active=useRef(true),generation=useRef(0),lock=useRef(false),requestId=useRef('');
 const refresh=useCallback(async()=>{const g=++generation.current;setLoading(true);setError('');try{const data=await loadModeration(status);if(active.current&&g===generation.current)setRows(data);}catch(e){if(active.current&&g===generation.current){setRows([]);setError((e as Error).message);}}finally{if(active.current&&g===generation.current)setLoading(false);}},[status]);
 useEffect(()=>{active.current=true;let live=true;Promise.resolve().then(()=>{if(live)refresh();});return()=>{live=false;active.current=false;};},[refresh]);
 const open=async(id:string)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');setDetail(null);setAction(null);setNote('');requestId.current='';try{const row=await loadReport(id);if(active.current)setDetail(row);}catch(e){if(active.current)setError((e as Error).message);}finally{lock.current=false;if(active.current)setBusy(false);}};
 const submit=async()=>{if(!detail||!action||lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');if(!requestId.current)requestId.current=commentId();try{await decideReport(detail,action,note,requestId.current);if(active.current){setNotice('Decisión guardada: '+decisionLabels[action]+'.');setAction(null);requestId.current='';setNote('');const next=await loadReport(detail.id);if(active.current){setDetail(next);await refresh();}}}catch(e){if(active.current)setError((e as Error).message);}finally{lock.current=false;if(active.current)setBusy(false);}};
 const choose=(next:Decision)=>{setAction(next);requestId.current='';setError('');};
 return <View style={s.screen}><ScreenHeader close={close} label="Volver a por ahí" disabled={busy}/><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={ui.kicker}>CUIDADO DE LA COMUNIDAD</Text><Text style={s.title}>Administración</Text><Text style={s.note}>Revisa cada caso y registra el motivo de tu decisión.</Text><View style={s.filters}>{(Object.keys(statusLabels) as ReportStatus[]).map(value=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:status===value}} disabled={busy||loading} onPress={()=>{setStatus(value);setDetail(null);setAction(null);setNotice('');}} style={[s.chip,status===value&&s.selected]}><Text style={s.name}>{statusLabels[value]}</Text></Pressable>)}</View><AdminButton label={loading?'Actualizando…':'Actualizar reportes'} onPress={()=>{setDetail(null);setAction(null);refresh();}} disabled={loading||busy}/>{!!notice&&<Text accessibilityRole="alert" style={s.note}>{notice}</Text>}{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}
 {detail?<View style={s.card}><AdminButton label="Volver a la lista" onPress={()=>{setDetail(null);setAction(null);}} disabled={busy}/><Text style={s.subtitle}>{kindLabels[detail.target_kind]} · {detail.reason}</Text><Text style={s.note}>Autor: {detail.author||'No disponible'} · {new Date(detail.created_at).toLocaleString('es-MX')}</Text><Text style={s.name}>Lo que se reportó</Text><Text style={s.body}>{detail.preview||'El contenido ya no está disponible.'}</Text>{detail.media_url&&(detail.media_kind==='image'?<Image accessibilityLabel="Imagen reportada" source={{uri:detail.media_url}} style={s.media} resizeMode="contain"/>:<ReportVideo key={detail.media_url} uri={detail.media_url}/>)}<Text style={s.name}>Detalles del reporte</Text><Text style={s.body}>{detail.details||'Sin detalles adicionales.'}</Text><Text style={s.note}>Estado: {statusLabels[detail.status]}. Contenido {detail.hidden?'oculto':'sin ocultación de administración'}.</Text>{detail.target_kind==='profile'&&<Text style={s.note}>Puedes revisar este perfil o descartar el reporte. La suspensión de cuentas se añadirá en otro paso.</Text>}{detail.target_kind==='story'&&<Text style={s.note}>Restaurar una story conserva su vencimiento original de 24 horas.</Text>}
 {action?<View style={s.confirm}><Text style={s.subtitle}>{decisionLabels[action]}</Text><Text style={s.note}>{action==='hide'?'Se ocultará para los usuarios. El archivo se conserva y podrás restaurarlo. Los enlaces cargados antes pueden seguir funcionando hasta vencer.':action==='restore'?'Se retirará la ocultación de administración. Las reglas de bloqueo, borrado propio y vencimiento siguen aplicando.':'Cambiará el estado del reporte; la visibilidad del contenido se conserva.'}</Text><TextInput accessibilityLabel="Motivo de la decisión" value={note} onChangeText={value=>{setNote(value);requestId.current='';}} editable={!busy} multiline maxLength={1000} placeholder="Explica el motivo…" placeholderTextColor={p.muted} style={s.input}/><AdminButton label={busy?'Guardando…':'Confirmar decisión'} onPress={()=>submit()} disabled={busy||note.trim().length<3}/><AdminButton label="Cancelar decisión" onPress={()=>{setAction(null);requestId.current='';}} disabled={busy}/></View>:<>{detail.target_kind!=='profile'&&detail.available&&<AdminButton label={detail.hidden?'Restaurar contenido':'Ocultar contenido'} onPress={()=>choose(detail.hidden?'restore':'hide')} disabled={busy}/>}<AdminButton label="Marcar como revisado" onPress={()=>choose('review')} disabled={busy}/><AdminButton label="Descartar reporte" onPress={()=>choose('dismiss')} disabled={busy}/>{detail.status!=='pending'&&<AdminButton label="Reabrir reporte" onPress={()=>choose('reopen')} disabled={busy}/>}</>}
 <Text style={s.subtitle}>Historial de decisiones</Text>{!detail.history.length&&<Text style={s.note}>Todavía no hay decisiones.</Text>}{detail.history.map((entry,i)=><View key={entry.created_at+i} style={s.history}><Text style={s.name}>{decisionLabels[entry.action]}</Text><Text style={s.body}>{entry.note}</Text><Text style={s.note}>{new Date(entry.created_at).toLocaleString('es-MX')}</Text></View>)}{detail.history.length===20&&<Text style={s.note}>Mostramos las últimas 20 decisiones de este reporte.</Text>}</View>:<>{!loading&&!busy&&!rows.length&&!error&&<Text style={s.note}>No hay reportes en esta lista.</Text>}{rows.map(row=><AdminButton key={row.id} label={kindLabels[row.target_kind]+' · '+row.reason+' · '+new Date(row.created_at).toLocaleString('es-MX')} onPress={()=>open(row.id)} disabled={busy||loading}/>)}{rows.length===50&&<Text style={s.note}>Mostramos 50 reportes. Los pendientes más antiguos aparecen primero; al resolverlos se cargarán los siguientes.</Text>}</>}
 </ScrollView></View>;
}
export const adminStyles=StyleSheet.create({screen:ui.screen,content:{...ui.content,maxWidth:650},title:ui.title,note:ui.note});
const s=StyleSheet.create({...ui,...adminStyles,subtitle:{fontSize:21,fontWeight:'800',letterSpacing:-.4,color:p.ink,marginVertical:15},name:{fontSize:12,fontWeight:'700',color:p.ink},filters:{flexDirection:'row',gap:8,flexWrap:'wrap',marginBottom:12},chip:{padding:12,borderRadius:14,backgroundColor:p.surface,minHeight:44,borderWidth:1,borderColor:p.line},selected:{backgroundColor:p.violetSoft,borderColor:'#DACCFA'},history:{borderBottomWidth:1,borderColor:p.line,paddingVertical:10},confirm:{padding:15,borderRadius:18,backgroundColor:p.violetSoft,marginVertical:12},media:{height:280,width:'100%',borderRadius:15,backgroundColor:p.ink},input:{...ui.input,minHeight:90,textAlignVertical:'top'}});
