import React from 'react';
import {View,Text,ScrollView,Pressable,StyleSheet} from 'react-native';
import {notificationText,type Notification} from '../lib/notifications';
type Props={userId:string|null;rows:Notification[];unread:number;loading:boolean;busy:boolean;error:string;refresh:()=>void;mark:()=>void;open:(row:Notification)=>void;close:()=>void;login:()=>void};
export default function NotificationsPanel(p:Props){
 const button=(label:string,action:()=>void,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled} onPress={action} style={[s.button,disabled&&{opacity:.5}]}><Text style={s.buttonText}>{label}</Text></Pressable>;
 return <View style={s.screen}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">{button('Cerrar notificaciones',p.close)}<Text style={s.title}>Tus notificaciones</Text>
 {!p.userId?<><Text style={s.note}>Inicia sesión para ver quién te sigue y las novedades de tus publicaciones.</Text>{button('Ir a mi cuenta',p.login)}</>:<><Text style={s.note}>{p.unread} sin leer</Text>{button(p.loading?'Actualizando…':'Actualizar avisos',p.refresh,p.loading||p.busy)}{button('Marcar todas como leídas',p.mark,p.loading||p.busy||!p.unread)}{!!p.error&&<Text accessibilityRole="alert" style={s.error}>{p.error}</Text>}{!p.loading&&!p.error&&!p.rows.length&&<Text style={s.note}>Todavía no tienes notificaciones. Aparecerán cuando otra persona te siga, dé me gusta o comente tus publicaciones.</Text>}
 {p.rows.map(row=><View key={row.id} style={[s.row,!row.read_at&&s.unread]}><Pressable accessibilityRole="button" accessibilityLabel={'Abrir aviso: '+notificationText(row)} disabled={p.busy} onPress={()=>p.open(row)}><Text style={s.text}>{!row.read_at?'● ':''}{notificationText(row)}</Text><Text style={s.note}>{new Date(row.created_at).toLocaleString('es-MX')}</Text><Text style={s.link}>{row.kind==='follow'?'Ver perfil':'Ver publicación'} · {row.read_at?'Leído':'Sin leer'}</Text></Pressable></View>)}{p.rows.length===50&&<Text style={s.note}>Mostramos los últimos 50 avisos. El contador incluye todos los avisos sin leer.</Text>}<Text style={s.note}>Los avisos se actualizan cada 30 segundos mientras la aplicación está abierta.</Text></>}
 </ScrollView></View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#faf9f5'},content:{padding:22,paddingTop:60,width:'100%',maxWidth:590,alignSelf:'center'},title:{fontSize:30,fontWeight:'700',color:'#243d31',marginVertical:18},note:{fontSize:13,color:'#536350',lineHeight:21,marginVertical:10},button:{backgroundColor:'#965337',padding:15,borderRadius:12,marginVertical:6},buttonText:{fontSize:13,color:'#fff',textAlign:'center',fontWeight:'600'},row:{padding:18,borderRadius:15,backgroundColor:'#eef1e8',marginVertical:7},unread:{borderWidth:1,borderColor:'#965337'},text:{fontSize:15,lineHeight:23,color:'#243d31'},link:{fontSize:13,color:'#965337'},error:{fontSize:13,color:'#9c3d24',marginVertical:12}});
