import React from 'react';
import {View,Text,ScrollView,Pressable,StyleSheet} from 'react-native';
import {notificationText,type Notification} from '../lib/notifications';
import {palette as c} from '../lib/theme';
import ui from '../lib/uiStyles';
import ScreenHeader from './ScreenHeader';
import Icon from './Icon';
type Props={userId:string|null;rows:Notification[];unread:number;loading:boolean;busy:boolean;error:string;refresh:()=>void;mark:()=>void;open:(row:Notification)=>void;close:()=>void;login:()=>void};
export default function NotificationsPanel(p:Props){
 const button=(label:string,action:()=>void,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled} onPress={action} style={[s.button,disabled&&{opacity:.5}]}><Text style={s.buttonText}>{label}</Text></Pressable>;
 return <View style={s.screen}><ScreenHeader close={p.close} label="Cerrar notificaciones"/><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
 {!p.userId?<View style={s.empty}><Icon name="bell" size={32} color={c.violet}/><Text style={s.note}>Inicia sesión para ver quién te sigue y las novedades de tus publicaciones.</Text>{button('Ir a mi cuenta',p.login)}</View>:<>{p.unread>0&&<Pressable accessibilityRole="button" disabled={p.loading||p.busy} onPress={p.mark} style={[s.mark,(p.loading||p.busy)&&{opacity:.5}]}><Text style={s.markText}>Marcar todas como leídas</Text></Pressable>}{!!p.error&&<Text accessibilityRole="alert" style={s.error}>{p.error}</Text>}{!p.loading&&!p.error&&!p.rows.length&&<View style={s.empty}><Icon name="bell" size={32} color={c.violet}/><Text style={s.note}>Todavía no tienes notificaciones. Aparecerán cuando otra persona te siga, dé me gusta o comente tus publicaciones.</Text></View>}
 {p.rows.map(row=><Pressable key={row.id} accessibilityRole="button" accessibilityLabel={'Abrir aviso: '+notificationText(row)} disabled={p.busy} onPress={()=>p.open(row)} style={[s.row,!row.read_at&&s.unread]}><View style={s.avatar}><Text style={s.initial}>{row.actor_name[0]?.toUpperCase()}</Text></View><View style={{flex:1,minWidth:0}}><Text style={s.text}>{notificationText(row)}</Text><Text style={s.date}>{new Date(row.created_at).toLocaleString('es-MX')}</Text><Text style={s.link}>{row.kind==='follow'?'Ver perfil':'Ver publicación'} · {row.read_at?'Leído':'Sin leer'}</Text></View>{!row.read_at&&<View accessibilityLabel="Sin leer" style={s.dot}/>}</Pressable>)}</>}
 </ScrollView></View>;
}
const s=StyleSheet.create({...ui,toolbar:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},count:{fontSize:11,fontWeight:'800',color:c.violet,backgroundColor:c.violetSoft,padding:9,borderRadius:10},refresh:{width:44,height:44,alignItems:'center',justifyContent:'center'},mark:{minHeight:44,justifyContent:'center',marginBottom:12},markText:{fontSize:12,fontWeight:'600',color:c.muted},row:{flexDirection:'row',alignItems:'flex-start',gap:10,padding:16,borderRadius:20,backgroundColor:c.surface,borderWidth:1,borderColor:c.line,marginVertical:6},unread:{backgroundColor:c.violetSoft,borderColor:'#DACCFA'},avatar:{width:34,height:34,borderRadius:12,backgroundColor:c.ink,alignItems:'center',justifyContent:'center'},initial:{fontSize:14,fontWeight:'800',color:c.lime},text:{fontSize:13,fontWeight:'600',lineHeight:21,color:c.ink},date:{fontSize:10,lineHeight:16,color:c.muted,marginTop:6},link:{fontSize:10,fontWeight:'700',color:c.violet,marginTop:7},dot:{width:7,height:7,borderRadius:4,backgroundColor:c.violet,marginTop:5},empty:{padding:20,backgroundColor:c.surface,borderWidth:1,borderColor:c.line,borderRadius:22,marginTop:12}});
