import React from 'react';
import {View,Text,ScrollView,Pressable,StyleSheet,Platform} from 'react-native';
import type {Review} from '../lib/posts';
import {palette as p} from '../lib/theme';
import Icon from './Icon';

type Props={review:Review;saved:boolean;busy:boolean;error:string;close:()=>void;save:()=>void;retry:()=>void;share?:()=>void;manage?:()=>void;report?:()=>void;block?:()=>void;children:React.ReactNode};
export default function ReviewDetails({review,saved,busy,error,close,save,retry,share,manage,report,block,children}:Props){
 return <View style={s.backdrop}><Pressable accessibilityRole="button" accessibilityLabel="Cerrar detalles" onPress={close} style={{flex:1}}/><View style={s.sheet}><View style={s.handle}/><View style={s.heading}><View style={s.tag}><Text style={s.tagText}>{review.category.toUpperCase()}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Cerrar detalles" onPress={close} style={s.close}><View style={{transform:[{rotate:'45deg'}]}}><Icon name="plus" size={23}/></View></Pressable></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}><Text style={s.title}>{review.place}</Text><View style={s.author}><View style={s.avatar}><Text style={s.initial}>{review.author[0]?.toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.name}>{review.author}</Text><Text style={s.note}>{review.cloud?'Una experiencia compartida':'Ejemplo ficticio'}</Text></View></View><View style={s.recommendation}><Text style={s.label}>SU RECOMENDACIÓN</Text><Text style={s.body}>{review.text||'Sin información adicional.'}</Text></View><View style={s.actions}><Pressable accessibilityRole="button" accessibilityLabel={saved?'Quitar de guardados':'Guardar lugar'} disabled={busy} onPress={save} style={[s.primary,busy&&{opacity:.5}]}><Icon name="bookmark" filled={saved} size={20}/><Text style={s.buttonText}>{saved?'Guardado':'Guardar lugar'}</Text></Pressable>{share&&<Pressable accessibilityRole="button" accessibilityLabel="Compartir esta reseña" onPress={share} style={s.secondary}><Icon name="arrow" size={20}/><Text style={s.buttonText}>Compartir</Text></Pressable>}</View>{!!error&&<><Text accessibilityRole="alert" style={s.error}>{error}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={retry} style={s.textButton}><Text style={s.controlText}>Reintentar interacciones</Text></Pressable></>}{manage&&<Pressable accessibilityRole="button" onPress={manage} style={s.textButton}><Text style={s.controlText}>Editar o eliminar mi reseña</Text></Pressable>}{(report||block)&&<View style={s.safety}>{report&&<Pressable accessibilityRole="button" onPress={report} style={s.textButton}><Text style={s.controlText}>Reportar publicación</Text></Pressable>}{block&&<Pressable accessibilityRole="button" onPress={block} style={s.textButton}><Text style={s.controlText}>Bloquear autor</Text></Pressable>}</View>}{children}</ScrollView></View></View>;
}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:'#17171C88'},sheet:{maxHeight:'86%',backgroundColor:p.surface,borderTopLeftRadius:28,borderTopRightRadius:28,paddingBottom:Platform.OS==='ios'?24:8,width:'100%',maxWidth:590,alignSelf:'center'},handle:{width:42,height:4,backgroundColor:p.line,borderRadius:4,alignSelf:'center',marginTop:12},heading:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:22,paddingTop:6},tag:{paddingHorizontal:10,paddingVertical:6,borderRadius:8,backgroundColor:p.violetSoft},tagText:{fontSize:9,letterSpacing:1,fontWeight:'800',color:p.violet},close:{width:44,height:44,alignItems:'center',justifyContent:'center'},content:{padding:22,paddingTop:6},title:{fontSize:30,lineHeight:35,fontWeight:'900',letterSpacing:-.9,color:p.ink,marginBottom:20},author:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:18},avatar:{width:38,height:38,borderRadius:14,backgroundColor:p.ink,alignItems:'center',justifyContent:'center'},initial:{fontSize:16,fontWeight:'800',color:p.lime},name:{fontSize:13,fontWeight:'700',color:p.ink},note:{fontSize:11,color:p.muted,marginTop:4},recommendation:{padding:17,borderRadius:18,backgroundColor:p.soft,marginBottom:14},label:{fontSize:9,fontWeight:'800',letterSpacing:1.4,color:p.muted,marginBottom:9},body:{fontSize:15,lineHeight:25,color:p.ink},actions:{flexDirection:'row',gap:10,flexWrap:'wrap'},primary:{flex:1,minWidth:125,minHeight:48,padding:13,borderRadius:15,backgroundColor:p.lime,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},secondary:{flex:1,minWidth:125,minHeight:48,padding:13,borderRadius:15,borderWidth:1,borderColor:p.line,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},buttonText:{fontSize:12,fontWeight:'700',color:p.ink},safety:{flexDirection:'row',flexWrap:'wrap',gap:10},textButton:{minHeight:44,justifyContent:'center',paddingHorizontal:4},controlText:{fontSize:11,fontWeight:'600',color:p.muted},error:{fontSize:13,lineHeight:21,color:p.error,marginTop:12}});
