import React,{useEffect,useRef,useState} from 'react';
import {View,Text,Pressable,TextInput,ScrollView,StyleSheet} from 'react-native';
import {loadBlocks,changeBlock,submitReport,reportReasons,type BlockedPerson,type ReportTarget} from '../lib/safety';
function Button({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button,disabled&&{opacity:.5}]}><Text style={s.buttonText}>{label}</Text></Pressable>;}
export function ReportForm({target,userId,close,login}:{target:ReportTarget;userId:string|null;close:()=>void;login:()=>void}){
 const [reason,setReason]=useState<string>(reportReasons[0]),[details,setDetails]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false);
 const alive=useRef(true),lock=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const send=async()=>{if(!userId||lock.current)return;lock.current=true;setBusy(true);setError('');try{await submitReport(userId,target,reason,details);if(alive.current)setSent(true);}catch(e){if(alive.current)setError((e as Error).message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
 return <View style={s.screen}><ScrollView contentContainerStyle={[s.content,{paddingTop:55}]} keyboardShouldPersistTaps="handled"><Button label="Cerrar reporte" onPress={close} disabled={busy}/><Text style={s.title}>Reportar contenido</Text><Text style={s.note}>{target.label}</Text>{!userId?<><Text style={s.note}>Inicia sesión para registrar un reporte.</Text><Button label="Ir a mi cuenta" onPress={login}/></>:sent?<Text accessibilityRole="alert" style={s.note}>Reporte registrado. Queda pendiente de revisión. Reportar no elimina el contenido automáticamente. Si ya lo habías reportado, conservamos tu reporte anterior.</Text>:<><Text style={s.note}>¿Cuál es el motivo?</Text>{reportReasons.map(r=><Pressable key={r} accessibilityRole="radio" accessibilityState={{checked:reason===r}} disabled={busy} onPress={()=>setReason(r)} style={s.row}><Text style={s.name}>{reason===r?'●':'○'} {r}</Text></Pressable>)}<Text style={s.note}>Detalles opcionales</Text><TextInput accessibilityLabel="Detalles del reporte" value={details} onChangeText={setDetails} maxLength={1000} editable={!busy} multiline style={s.input}/>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}<Button label={busy?'Registrando…':'Registrar reporte'} onPress={()=>send()} disabled={busy}/><Text style={s.note}>El reporte lo recibe la administración de por ahí. No se muestra al autor ni a otros usuarios.</Text></>}</ScrollView></View>;
}
export function BlockConfirm({userId,target,close,done,login}:{userId:string|null;target:{id:string;name:string};close:()=>void;done:()=>void;login:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const alive=useRef(true),lock=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const block=async()=>{if(!userId||lock.current)return;lock.current=true;setBusy(true);setError('');try{await changeBlock(userId,target.id,true);if(alive.current)done();}catch(e){if(alive.current)setError((e as Error).message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
 return <View style={s.screen}><ScrollView contentContainerStyle={[s.content,{paddingTop:55}]}><Button label="Cancelar bloqueo" onPress={close} disabled={busy}/><Text style={s.title}>Bloquear a {target.name}</Text><Text style={s.note}>Sus perfiles, publicaciones, stories y conversaciones se ocultarán entre ambas cuentas mientras haya una sesión iniciada. No podrán enviarse mensajes, seguirse ni interactuar con sus publicaciones. Se quitará el seguimiento entre ambos.</Text><Text style={s.note}>Puedes deshacerlo en Perfil → Personas bloqueadas. Los mensajes anteriores se conservan. Tus publicaciones públicas siguen siendo visibles para visitantes sin sesión.</Text>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}{userId?<Button label={busy?'Bloqueando…':'Confirmar bloqueo'} onPress={()=>block()} disabled={busy}/>:<><Text style={s.note}>Inicia sesión para bloquear a alguien.</Text><Button label="Ir a mi cuenta" onPress={login}/></>}</ScrollView></View>;
}
export function BlockedList({userId,onChange}:{userId:string;onChange:()=>void}){
 const [rows,setRows]=useState<BlockedPerson[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[success,setSuccess]=useState('');const alive=useRef(true),lock=useRef(false);
 useEffect(()=>{alive.current=true;let active=true;Promise.resolve().then(async()=>{if(!active)return;setBusy(true);setError('');try{const data=await loadBlocks();if(active)setRows(data);}catch(e){if(active)setError((e as Error).message);}finally{if(active)setBusy(false);}});return()=>{active=false;alive.current=false;};},[userId,attempt]);
 const unblock=async(id:string)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await changeBlock(userId,id,false);if(alive.current){setRows(p=>p.filter(r=>r.blocked_id!==id));setSuccess('Bloqueo retirado. Puedes volver a seguir a esta persona desde Buscar.');onChange();}}catch(e){if(alive.current)setError((e as Error).message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
 return <View style={{marginTop:25}}><Text style={s.name}>Personas bloqueadas</Text><Button label={busy?'Actualizando…':'Actualizar bloqueos'} onPress={()=>{setSuccess('');setAttempt(n=>n+1);}} disabled={busy}/>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}{!!success&&<Text accessibilityRole="alert" style={s.note}>{success}</Text>}{!busy&&!rows.length&&!error&&<Text style={s.note}>No has bloqueado a nadie.</Text>}{rows.map(r=><View key={r.blocked_id} style={s.row}><Text style={s.name}>{r.blocked_name} · @{r.blocked_handle}</Text><Button label={'Desbloquear a '+r.blocked_name} onPress={()=>unblock(r.blocked_id)} disabled={busy}/></View>)}</View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#faf9f5'},content:{padding:22,width:'100%',maxWidth:590,alignSelf:'center'},title:{fontSize:28,fontWeight:'700',color:'#243d31',marginVertical:15},note:{fontSize:13,color:'#536350',lineHeight:22,marginVertical:10},row:{paddingVertical:13,borderBottomWidth:1,borderColor:'#e2e7d8'},name:{fontSize:15,fontWeight:'600',color:'#243d31'},button:{backgroundColor:'#965337',padding:15,borderRadius:12,marginVertical:6},buttonText:{color:'#fff',textAlign:'center',fontWeight:'600'},input:{backgroundColor:'#e9eee4',padding:15,borderRadius:12,color:'#243d31',minHeight:95},error:{color:'#9c3d24',marginVertical:12}});
