// Complete these with the owner's confirmed legal identity/address before publication.
export const LEGAL_VERSION='2026-10-07';
export const privacyContact='juan.perez.cns@hotmail.com';
export const legalOperator:{name:string|null;address:string|null}={name:null,address:null};
export const legalReady=!!legalOperator.name&&!!legalOperator.address;
export type LegalSection={title:string;text:string};
export const privacySections:LegalSection[]=[
 {title:'Quién es responsable',text:`Por Ahí Social es una beta de recomendaciones. Responsable: ${legalOperator.name||'pendiente de confirmar'}. Domicilio para privacidad: ${legalOperator.address||'pendiente de confirmar'}. Contacto: ${privacyContact}.`},
 {title:'Qué información guardamos',text:'Correo, identificador de cuenta y datos de acceso; nombre, @usuario y biografía; fotos y videos, lugares y descripciones que publiques; seguidores, likes, guardados, comentarios, mensajes, avisos, bloqueos y reportes. Con Google recibimos tu identificador, correo, nombre y foto de perfil cuando el proveedor los facilita. La contraseña se administra a través de Supabase Auth; la app no la muestra a otros usuarios.'},
 {title:'Para qué se usa',text:'Para iniciar sesión, guardar tu perfil, publicar y mostrar recomendaciones, buscar personas, conservar tu biblioteca, comunicarte con otra cuenta y atender reportes o solicitudes de soporte. La beta no tiene pagos, anuncios ni venta de datos. Si se incorporan finalidades distintas, se explicarán antes de activarlas.'},
 {title:'Qué es público y qué es privado',text:'Tu nombre de perfil, @usuario, biografía, reseñas y comentarios visibles pueden ser consultados por otras personas, incluso sin cuenta. Tus stories se muestran durante 24 horas. Los guardados, la lista de cuentas que sigues, los bloqueos y tus avisos son privados para tu cuenta. Los mensajes están disponibles para las dos personas de la conversación; la administración puede revisar un mensaje que haya sido reportado. No hay cifrado de extremo a extremo.'},
 {title:'Fotos, permisos y ubicación',text:'Eliges las fotos o videos que deseas subir; la app no importa automáticamente tu galería o contactos. Esta beta no utiliza GPS: Cerca de ti todavía es una demostración. Los lugares que escribas serán públicos. Los archivos pueden conservar metadatos del original; revisa qué información contienen y evita documentos, domicilios particulares, datos sensibles o imágenes de otras personas sin autorización.'},
 {title:'Servicios que hacen funcionar la app',text:'Supabase administra cuentas, base de datos y archivos; Netlify sirve la web; Google interviene si eliges ese acceso. Estos servicios pueden procesar datos técnicos, como IP, navegador y registros de seguridad, y operar fuera de México. El navegador o dispositivo conserva la sesión para recordar tu acceso. No hemos añadido analítica publicitaria. No compartas contraseñas ni códigos de acceso con soporte.'},
 {title:'Cuánto tiempo se conserva',text:'El contenido y las interacciones permanecen mientras exista la cuenta. Al vencer, una story deja de mostrarse, pero su archivo no se borra automáticamente todavía. Eliminar cuenta retira archivos propios de la app y datos asociados de la base activa. Copias descargadas por otras personas, cachés, respaldos y registros técnicos de proveedores no desaparecen con el botón ni están sujetos a una promesa de borrado instantáneo.'},
 {title:'Tus controles y solicitudes',text:`Puedes editar nombre, usuario y biografía en Perfil; quitar guardados y likes; retirar tus comentarios; bloquear personas y solicitar Eliminar cuenta. Para acceso, rectificación, cancelación, oposición, revocación de consentimiento o limitación del uso de datos, escribe a ${privacyContact} con el asunto Privacidad Por Ahí, tu @usuario, lo que solicitas y un medio de respuesta. Comprobaremos que la solicitud corresponde al titular; no envíes identificaciones o contraseñas en el primer mensaje. Se atenderá de acuerdo con los requisitos y plazos aplicables.`},
 {title:'Cambios y contacto',text:`La versión y fecha del aviso aparecerán en esta página. Los cambios relevantes se comunicarán dentro de la app antes de aplicar nuevas finalidades cuando corresponda. Puedes usar ${privacyContact} para dudas o reportar un problema de privacidad.${legalReady?'':' Este borrador necesita completar la identidad y domicilio del responsable antes de abrir la beta a nuevos usuarios.'}`},
];
export const termsSections:LegalSection[]=[
 {title:'Una beta gratuita',text:'Por Ahí Social permite compartir recomendaciones mediante fotos y videos. Esta etapa está en pruebas: puede haber fallos, mantenimiento y cambios de funciones. La beta inicial propuesta es para personas mayores de 18 años. No hay compras ni suscripciones activadas. Conserva una copia de tus archivos importantes fuera de la app.'},
 {title:'Tu cuenta',text:'Usa una cuenta que te pertenezca y protege su acceso. No suplantes personas ni compartas contraseñas. Las funciones que guardan actividad requieren iniciar sesión y completar el perfil. Puedes explorar el contenido público sin registrarte.'},
 {title:'Tus publicaciones',text:'Conservas los derechos que tengas sobre tu contenido. Al publicarlo, permites alojarlo y mostrarlo para operar las funciones de Por Ahí. Sube solo material propio o que tengas autorización para utilizar. Respeta privacidad, derechos de imagen y derechos de autor. El permiso para mostrarlo termina al retirarlo de la app; las copias o compartidos que hayan hecho otras personas pueden permanecer fuera de ella.'},
 {title:'Recomendaciones claras',text:'Cuenta tu experiencia con honestidad. Si recibiste dinero, una invitación o un beneficio por recomendar, indícalo claramente. Evita reseñas falsas, spam, fraude, acoso, amenazas, discriminación y publicaciones ilegales. La app no garantiza la calidad de un lugar, precios, horarios ni la veracidad de todas las reseñas.'},
 {title:'Reportes y moderación',text:'Puedes reportar contenido y bloquear cuentas. La administración revisa reportes y puede ocultar contenido conforme a estas reglas; bloquear no elimina una conversación anterior. Para solicitar revisión de una medida, escribe al contacto de soporte indicando tu @usuario y la publicación, sin incluir contraseñas ni códigos.'},
 {title:'Salir de la beta',text:'Eliminar cuenta requiere confirmación y un inicio de sesión reciente. Se retiran tu perfil, archivos propios, reseñas, stories, likes, guardados, comentarios, seguimiento, avisos, bloqueos y reportes asociados. En esta beta también se borran completas tus conversaciones de dos personas, incluidos los mensajes de la otra cuenta. Es irreversible; si falla la conexión, hay que reintentar para completar los pasos pendientes. La última cuenta administradora necesita que se asigne otra antes de eliminarse.'},
 {title:'Soporte y cambios',text:`Contacto: ${privacyContact}. El tratamiento de datos se explica en el aviso de privacidad. Si se introducen pagos, publicidad o condiciones distintas se comunicarán previamente; esta página no autoriza cobros futuros.${legalReady?'':' Estas condiciones son un borrador para revisión del responsable de la beta.'}`},
];
